# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  # - 3.5
  # - 3.4

env:
  matrix:
    - NODE=8.15.0
    - NODE=10.15.0

matrix:
  fast_finish: true

services:
  - mongodb

# Command to install dependencies
install: 
  - pip install -U tox-travis
  - nvm install ${NODE}
  - node --version
  - npm install -g gulp-cli

# Command before to run tests
before_script:
  - npm -C client install

# Command to run tests
script: 
  - tox # test back-end
  - npm -C client run test:karma # test front-end


deploy:
  # Automatically build and deploy documentation to GitHub Pages after every
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6
      condition: $NODE = 10.15.0
