version: "3"
services:
  db:
    image: mongo:4.0
    container_name: db
    ports:
      - "27018:27017"
    command: bash -c "mongod --port 27017 --dbpath /db/data --logpath /db/log/docker.log --fork && mongorestore --db mtv /db/dump/mtv/ "
    volumes:
      - E:\mongo_instance_docker\data:/db/data
      - E:\mongo_instance_docker\log:/db/log
      - E:\mongo_instance_docker\dump:/db/dump
  web:
    build: .
    container_name: mtv
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: mtv run --env production -v
    volumes:
      - .:/mtv
