version: "3"
services:
  db:
    image: mongo:4.0
    container_name: db
    ports:
      - "27017:27017"
    command: mongod --port 27017 --dbpath /data/mtv --logpath /data/logs/mtv.log
    volumes:
      - db-data:/data/mtv
      - db-logs:/data/logs
  web:
    build: .
    container_name: mtv
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: mtv run --env production
    volumes:
      - .:/mtv
volumes:
  db-data:
  db-logs:
